### ISSUE TITLE
DTD Prohibited

### ISSUE THREAD

**Issue by mkheyer** [Sitefinity/SitefinityResources#11]
Hello,

I have an issue when trying to open those workflows in VS2015, I got an error saying that DTD is prohibited and cannot open the workflow in the workflow designer. I looked at the file directly and didn't find any thing related to DTD in it.

**Comment by gg3orgiev** [comment]
Hi mkheyer, 

Make sure to include the *.xamlx files in your SitefinityWebApp project before opening them as they refer namespaces which cannot be loaded when opening the files separately. I have successfully opened the workflows in the XAML Designer with both VS 2012 and VS 2015. If the issue still persists, please check your Visual Studio Settings. 

Best Regards,
Georgi
